### PR TITLE
Add runbook for concepts reindexer

### PR DESCRIPTION
**Pull request by MiroslavGatsanoga**
# Description

## What

Add runbook for Concepts ElasticSearch reindexer.

## Why

[JIRA ticket](https://financialtimes.atlassian.net/browse/UPPSF-1181).

## Anything, in particular, you'd like to highlight to reviewers

Keep in mind that code for the reindexer is in this repo but the mapping and the helm files are in https://github.com/Financial-Times/concept-search-index-mapping.

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [ ] Feature
- [X] Documentation
- [ ] Breaking change
- [X] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

### CODE REVIEW

**Review by ivan-p-nikolov — APPROVED** [review]

**Review by karsov — COMMENTED** [review]
I am pretty sure that the runbook for the concept reindexer shouldn't be in this repo but in `concept-search-index-mapping` because this repo is something like a library.

Otherwise the information looks OK.

**Comment by MiroslavGatsanoga** [comment]
> I am pretty sure that the runbook for the concept reindexer shouldn't be in this repo but in concept-search-index-mapping because this repo is something like a library.

@karsov This repo contains the whole application code not just a library, while the `concept-search-index-mapping` contains only  configuration files. Actually is the `elasticsearch-reindexer` being used as a base for any other service?

**Comment by karsov** [comment]
> > I am pretty sure that the runbook for the concept reindexer shouldn't be in this repo but in concept-search-index-mapping because this repo is something like a library.
> 
> @karsov This repo contains the whole application code not just a library, while the `concept-search-index-mapping` contains only configuration files. Actually is the `elasticsearch-reindexer` being used as a base for any other service?

You are correct but to me the runbook should go together with the deployment files.

**Comment by MiroslavGatsanoga** [comment]
@ivan-p-nikolov any thoughts on "runbook should go together with the deployment files"?

**Comment by ivan-p-nikolov** [comment]
> @ivan-p-nikolov any thoughts on "runbook should go together with the deployment files"?

A runbook describes a system. And the system is defined by its deployments so it sound logical to be with the deployment files.

**Pull request closed without merging**
